version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/test
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStart:
    - location: ./scripts/reload-pm2.sh
      timeout: 300
      runas: ec2-user

